### ISSUE TITLE
Focus student picture upload

### ISSUE THREAD

**Issue by masonclassicalacademy** [masonclassicalacademy/backlog#1]
Student pictures need to be uploaded to focus when they arrive this year. Mr. Hull request to help with attendance taking, etc.

**Comment by mca-it** [comment]
Had to call support desk and get access direction sto citrix workspace for collier and also submit accesses to the RIPphoto share on their network. 

I was able to make citrix workspace work and login/authenticate after I setup Duo mobile for MFA, but the shared drive is still not open.

**Comment by mca-it** [comment]
Had to work with support to add a few different apps to the citrix workspace. After a few reconnects was able to successfully navigate to the photoRIP share and upload our photos. There were a handful that errored out due to no longer being current students at MCA, but the vast majority (1370+) uploaded successfully.

I did a spot check on several students, and didn't seem to see their pictures updated - whether they had no picture or an outdated one currently. There must be a batch job or something. I will check again tomorrow to see if the updates took.

**Comment by masonclassicalacademy** [comment]
Spot checks this morning revealed the photos have started to change to the updated pictures.
